### ISSUE TITLE
Step 2: Choose your wand

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/broadcasting-spells#15]
The CGI definition box seems out of place after the 'Casting spells needs a wand' text. It’s sort of linked, but not really. Could we move this closer to the into text and reword the intro to something like: 'In this step, you will set the scene, choose your wand and create your own computer-generated magic'. Then there's a more direct link to why we've included this definition in this step.

**Comment by libxx1** [comment]
Oh yeah that's great. I've updated the step intro and moved the boxout directly underneath it. Does that work for you @megwangrpf ?
