### ISSUE TITLE
Step 3: The shrink spell

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/broadcasting-spells#16]
This could very much be user-error, but I was unable to get the shrinking sprite and sound to work when the green flag was clicked. So I could either click the green flag and have my wand move with my cursor, or click the red stop button and use my mouse cursor to click on the shrink button. I had a look at the completed project and couldn't figure it out. Again, very likely it's me, but just thought I'd mention it.

**Comment by libxx1** [comment]
Did that just happen on the shrink button? I think it might be the position fo the wand tip getting in the way - it needs to be away from the crosshair. @megwangrpf If you've still got your Scratch project could I take a look to see if there's anything I need to change/make clearer in the instructions.

**Comment by megwangrpf** [comment]
I couldn't recreate it, @libxx1, so definitely user error!
