### ISSUE TITLE
Step 8: Upgrade your project

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/broadcasting-spells#17]
We’ve suggested using the Scratch backpack to share sprites with friends, but in the expandable info, it says you can only use your own backpack. If it's possible to share sprites with friends using the backpack, then we'll need more info on how.

**Comment by libxx1** [comment]
I've updated it to read "your Scratch backpack" and added a few sentences about the the process. Do you think that's the right amount of info @megwangrpf and could you reword if needed please. Ta

**Comment by megwangrpf** [comment]
Brilliant wording, @libxx1! That's perfect. Thank you!
