### ISSUE TITLE
Step 9: What next?

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/broadcasting-spells#18]
The button at the bottom says ‘What’s next?’ instead of ‘What next?’ I wasn't sure where this text is located.

**Comment by libxx1** [comment]
I'm going to close this issue. @megwangrpf It's with digital to fix the flow of the end pages. Project currently have a 'What next?' step that tells you which project/path to go to next and a second 'What's next' step that collects feedback. It's in plan for this quarter.
