### ISSUE TITLE
Overall: expandable boxes

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/broadcasting-spells#21]
My understanding is that the pull-down/expandable boxes (I’m sure the terminology is all wrong, please educate me!) text is stored somewhere else and that eventually, it’ll come up for copy-edit again. 

I did copy-edit one in one project, but was not able to in another as there was link rather than text. Just wanted to flag it in case there's a way I can help make them more consistent.

**Comment by libxx1** [comment]
Yep the 'ingredients' have their own repositories in github. The name of the ingredient/repository is shown in triple brackets '[[[[[[scratch-backpack]]]]]]'. If the info is just to be used once but we want it too appear like an ingredient then you'll see it inside 'collapse' markdown on the page so it can be CE at the time you're doing the step.

Are you ok to CE the ingredients as you reach them by going to that repository or would you prefer another approach?
